# Generated by Django 5.2.8 on 2025-12-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studysession_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='study_spaced_repetition',
            field=models.BooleanField(default=True, help_text='Enable spaced repetition for study mode'),
        ),
        migrations.AddField(
            model_name='deck',
            name='test_sequential',
            field=models.BooleanField(default=False, help_text='Show cards sequentially in test mode'),
        ),
        migrations.AddField(
            model_name='deck',
            name='test_shuffle',
            field=models.BooleanField(default=True, help_text='Shuffle cards in test mode'),
        ),
    ]
