# Generated by Django 5.2.8 on 2025-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deck_description_deck_study_spaced_repetition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
