# Generated by ChatGPT on 2026-01-25
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cardreview_studyevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('shuffle', 'Shuffle'), ('sequential', 'Sequential')], max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_seconds', models.IntegerField(blank=True, null=True)),
                ('score_percent', models.FloatField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='api.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('elapsed_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.testattempt')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='api.card')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('attempt', 'card')},
            },
        ),
    ]
