[project]
name = "bilimdeck-backend"
version = "0.1.0"
description = "BilimDeck Django backend"
requires-python = ">=3.12"
dependencies = [
  "django==5.2.8",
  "djangorestframework==3.16.1",
  "djangorestframework-simplejwt==5.3.1",
  "django-cors-headers==4.9.0",
  "python-dotenv==1.2.1",
  "dj-database-url==3.1.0",
  "whitenoise==6.11.0",
  "gunicorn==23.0.0",
  "psycopg[binary]==3.3.2"
]

[tool.uv]
package = false

[tool.uv.sources]
